[project]
channels = ["conda-forge"]
description = "Neurospin/Baobab/GAIA website"
name = "neurospin_gaia"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
gaia-website = { cmd="bundle exec jekyll serve --livereload --port 8080"}

[dependencies]
ruby = ">=3.3.3,<4"
gcc = ">=14.1.0,<15"
gxx = ">=14.1.0,<15"
pybtex = ">=0.24.0,<0.25"
gfortran = ">=14.1.0,<15"

[activation]
scripts = ["neurospin_gaia.sh"]